### ISSUE TITLE
when building bzip2 for armv5, gcc complains of unknown flag -m64

### ISSUE THREAD

**Issue by windbender** [conan-community/conan-bzip2#19]
output is:

`
Scanning dependencies of target bz2
[ 10%] Building C object CMakeFiles/bz2.dir/blocksort.c.o
[ 20%] Building C object CMakeFiles/bz2.dir/compress.c.o
[ 30%] Building C object CMakeFiles/bz2.dir/bzlib.c.o
armv5-unknown-linux-gnueabi-gcc: error: unrecognized command line option '-m64'
CMakeFiles/bz2.dir/build.make:62: recipe for target 'CMakeFiles/bz2.dir/blocksort.c.o' failed
make[2]: *** [CMakeFiles/bz2.dir/blocksort.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
armv5-unknown-linux-gnueabi-gcc: error: unrecognized command line option '-m64'
armv5-unknown-linux-gnueabi-gcc: error: unrecognized command line option '-m64'
CMakeFiles/bz2.dir/build.make:88: recipe for target 'CMakeFiles/bz2.dir/compress.c.o' failed
make[2]: *** [CMakeFiles/bz2.dir/compress.c.o] Error 1
CMakeFiles/bz2.dir/build.make:75: recipe for target 'CMakeFiles/bz2.dir/bzlib.c.o' failed
make[2]: *** [CMakeFiles/bz2.dir/bzlib.c.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/bz2.dir/all' failed
make[1]: *** [CMakeFiles/bz2.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
bzip2/1.0.6@conan/stable: 
bzip2/1.0.6@conan/stable: ERROR: Package 'b869e6c05cb587ad588e5ec485deb62012ec7b93' build failed
bzip2/1.0.6@conan/stable: WARN: Build folder /home/chschaef/.conan/data/bzip2/1.0.6/conan/stable/build/b869e6c05cb587ad588e5ec485deb62012ec7b93
ERROR: bzip2/1.0.6@conan/stable: Error in build() method, line 51
	cmake.build(build_dir=".")
	ConanException: Error 512 while executing cmake --build '.' '--' '-j3'
`

I believe the -m64 flag is usually reserved for compiles of x86 code.   However as of yet I haven't figured out how to turn it off in context of an Armv5 build.

**Comment by lasote** [comment]
Let me check

**Comment by lasote** [comment]
Can you paste here the profile (or the default) you are using?

**Comment by windbender** [comment]
This build is in the context of the dockcross toolchain for armv5. 
so the following should demonstrate the problem:

docker run --rm dockcross/linux-armv5 >./dockcrossarmv5
chmod +x ./dockcrossarmv5
./dockcrossarmv5  conan install bzip2/1.0.6@conan/stable --build bzip2

To be clear, the problem here could be with the dockcross tool chain, but I have seen it properly compile other codebases to armv5, so my initial suspicion was with the bzip2 package.

**Comment by lasote** [comment]
The issue is that Conan generates the default profile and detects that the running machine is `x86_64` because it is what it is. So you need to specify the correct settings to Conan, something like:

`./dockcrossarmv5 conan install bzip2/1.0.6@conan/stable --build bzip2 -s arch=armv6`

Note that I put `armv6` because `armv5` is not in the generic `settings.yml` file. You could use the `conan config install` (https://docs.conan.io/en/latest/mastering/sharing_settings_and_config.html) command to install a good default profile for the machine and a customized `settings.yml`.

Any way we could add `armv5` to the base settings.yml, we just thought that it is very old to be used, but we are open to adding it. Please open an issue at https://github.com/conan-io/conan to include it in following versions by default.

**Comment by windbender** [comment]
@lasote   Thanks.  I did progress further yesterday using a profile file.  At this time I'm using Armv7 as the arch within the conan profile, even though the toolchain is officially an armv5 chain. (using dockcross ).  If I run across a problem with this approach I will certainly open a ticket for an armv5 arch value.  I will close this. sorry I was slow.
